import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/terms")({
  component: TermsPage,
  head: () => ({
    meta: [
      { title: "Terms of Service — WeekWise Finance" },
      { name: "description", content: "WeekWise Finance terms of service. Subscription terms, acceptable use, liability limits, and legal agreements." },
    ],
  }),
});

function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 pt-8 pb-20">
      <div className="mb-8">
        <Link to="/" className="text-sm font-medium text-indigo-600 hover:text-indigo-800">
          ← Back to WeekWise Finance
        </Link>
        <h1 className="mt-4 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">
          Terms of Service
        </h1>
        <p className="mt-2 text-sm text-gray-400">Last updated: July 17, 2026</p>
      </div>

      <div className="prose prose-gray max-w-none space-y-6 text-sm leading-relaxed">
        <section>
          <h2 className="text-xl font-bold text-gray-900">1. Acceptance of Terms</h2>
          <p className="mt-2 text-gray-600">
            By accessing or using WeekWise Finance ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service. We reserve the right to update these terms at any time; continued use after changes constitutes acceptance.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900">2. Description of Service</h2>
          <p className="mt-2 text-gray-600">
            WeekWise Finance is a personal finance tool that automatically categorizes your transactions, provides weekly spending insights, and offers AI-powered financial coaching. The Service is not a financial advisor, broker, or banking institution. It is a data analysis and visualization tool intended for informational purposes only.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900">3. Financial Disclaimer</h2>
          <div className="mt-2 rounded-lg border border-amber-200 bg-amber-50 p-4">
            <p className="font-medium text-amber-800">Important Disclaimer</p>
            <p className="mt-1 text-amber-700">
              WeekWise Finance is not a financial advisor, certified financial planner, or registered investment advisor. The insights, recommendations, and coaching provided by the Service are generated by artificial intelligence and are for informational and educational purposes only. They do not constitute financial, investment, tax, or legal advice.
            </p>
            <p className="mt-2 text-amber-700">
              You should consult with a qualified financial professional before making any financial decisions. Past spending patterns and trends do not guarantee future results. The Service may not capture all aspects of your financial situation, and you should not rely solely on its recommendations.
            </p>
          </div>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900">4. Account Registration</h2>
          <p className="mt-2 text-gray-600">
            You must create an account to use the Service. You are responsible for maintaining the confidentiality of your login credentials and for all activities under your account. You must provide accurate, current, and complete information during registration.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900">5. Subscription and Billing</h2>
          <div className="mt-2 space-y-3 text-gray-600">
            <h3 className="font-semibold text-gray-800">5.1 Free Trial</h3>
            <p>New users receive a 14-day free trial. No payment method is required to start the trial.</p>

            <h3 className="font-semibold text-gray-800">5.2 Subscription Plans</h3>
            <p>After the trial, continued access requires a paid subscription. We offer monthly ($7.99/month) and annual ($79.99/year) plans. Prices are subject to change with 30 days' notice.</p>

            <h3 className="font-semibold text-gray-800">5.3 Payment Processing</h3>
            <p>All payments are processed securely by Stripe. We do not store your payment card details. By subscribing, you authorize Stripe to charge your payment method on the agreed schedule.</p>

            <h3 className="font-semibold text-gray-800">5.4 Auto-Renewal</h3>
            <p>Subscriptions automatically renew at the end of each billing period unless cancelled before the renewal date. You can cancel at any time from your account settings.</p>

            <h3 className="font-semibold text-gray-800">5.5 Refund Policy</h3>
            <p>We do not offer refunds for partial billing periods. If you cancel, you will retain access to the Service until the end of your current billing period. Annual subscribers who cancel within the first 14 days of their annual term may request a pro-rated refund for the remaining months.</p>
          </div>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900">6. Acceptable Use</h2>
          <p className="mt-2 text-gray-600">You agree not to:</p>
          <ul className="mt-2 list-disc space-y-1 pl-5 text-gray-600">
            <li>Use the Service for any illegal purpose or in violation of any applicable laws</li>
            <li>Attempt to access, tamper with, or probe the security of the Service, servers, or connected systems</li>
            <li>Upload or transmit viruses, malware, or any malicious code</li>
            <li>Interfere with or disrupt the integrity or performance of the Service</li>
            <li>Use the Service to store or process sensitive financial information beyond what is necessary for the Service's intended use</li>
            <li>Reverse engineer, decompile, or disassemble any aspect of the Service</li>
            <li>Use the Service in a way that could harm minors or violate their privacy rights</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900">7. Data Privacy and Security</h2>
          <p className="mt-2 text-gray-600">
            Your use of the Service is also governed by our <Link to="/privacy" className="text-indigo-600 hover:underline">Privacy Policy</Link>. We implement industry-standard security measures to protect your data. However, no method of transmission or storage is 100% secure, and we cannot guarantee absolute security.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900">8. Third-Party Services</h2>
          <p className="mt-2 text-gray-600">
            The Service integrates with third-party services including Plaid (for bank account linking), Stripe (for payment processing), and OpenAI (for AI features). Your use of these services is subject to their respective terms and privacy policies. We are not responsible for the acts or omissions of these third parties.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900">9. Intellectual Property</h2>
          <p className="mt-2 text-gray-600">
            The Service, including its code, design, branding, and content, is owned by WeekWise Finance and is protected by copyright, trademark, and other intellectual property laws. You may not reproduce, distribute, modify, or create derivative works without our express written permission.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900">10. Limitation of Liability</h2>
          <div className="mt-2 rounded-lg border border-red-200 bg-red-50 p-4">
            <p className="text-sm text-red-700">
              To the maximum extent permitted by applicable law, WeekWise Finance, its officers, employees, and affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, use, or goodwill, arising from or related to your use of the Service. This includes, but is not limited to, any financial losses resulting from following or failing to follow the Service's insights, recommendations, or coaching.
            </p>
            <p className="mt-2 text-sm text-red-700">
              Our total liability for any claim arising from the Service is limited to the amount you have paid us in the 12 months preceding the claim.
            </p>
          </div>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900">11. Disclaimer of Warranties</h2>
          <p className="mt-2 text-gray-600">
            The Service is provided "as is" and "as available" without warranties of any kind, either express or implied. We do not warrant that the Service will be uninterrupted, error-free, secure, or that all insights or categorizations will be accurate. The AI-powered features are provided for informational purposes and may contain errors or inaccuracies.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900">12. Termination</h2>
          <div className="mt-2 space-y-3 text-gray-600">
            <h3 className="font-semibold text-gray-800">12.1 By You</h3>
            <p>You may cancel your subscription at any time from your account settings. Your access will continue until the end of your current billing period.</p>

            <h3 className="font-semibold text-gray-800">12.2 By Us</h3>
            <p>We reserve the right to suspend or terminate your access to the Service if you violate these terms, engage in fraudulent or illegal activity, or if your conduct could harm other users or the Service. We will provide notice when possible.</p>

            <h3 className="font-semibold text-gray-800">12.3 Effect of Termination</h3>
            <p>Upon termination, your access to the Service will cease. We will retain your data for 30 days after termination to allow for reactivation or data export, after which it will be permanently deleted.</p>
          </div>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900">13. Dispute Resolution</h2>
          <div className="mt-2 space-y-3 text-gray-600">
            <h3 className="font-semibold text-gray-800">13.1 Governing Law</h3>
            <p>These terms shall be governed by and construed in accordance with the laws of the State of California, without regard to its conflict of law provisions.</p>

            <h3 className="font-semibold text-gray-800">13.2 Informal Resolution</h3>
            <p>Before filing any claim, you agree to attempt to resolve the dispute informally by contacting us at <a href="mailto:support@weekwise.app" className="text-indigo-600 hover:underline">support@weekwise.app</a>. We will work in good faith to resolve the issue within 30 days.</p>

            <h3 className="font-semibold text-gray-800">13.3 Binding Arbitration</h3>
            <p>Any dispute not resolved informally shall be resolved through binding arbitration in San Francisco, California, administered by the American Arbitration Association. Each party shall bear its own costs and fees. This clause does not prevent either party from seeking injunctive relief in court for intellectual property violations or unauthorized access.</p>

            <h3 className="font-semibold text-gray-800">13.4 Class Action Waiver</h3>
            <p>You agree to resolve disputes on an individual basis and waive the right to participate in any class action, class arbitration, or representative proceeding.</p>
          </div>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900">14. Changes to Terms</h2>
          <p className="mt-2 text-gray-600">
            We may modify these terms at any time. Material changes will be notified via email or through the Service. Continued use after changes take effect constitutes acceptance of the new terms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900">15. Contact</h2>
          <p className="mt-2 text-gray-600">
            For questions about these terms, please contact us at <a href="mailto:support@weekwise.app" className="text-indigo-600 hover:underline">support@weekwise.app</a>.
          </p>
        </section>
      </div>
    </div>
  );
}