/**
 * Trial Reminder Email Template
 * 
 * Reference for the HTML template used in src/lib/email.ts.
 * The actual HTML is generated by the `trialReminderHtml()` function.
 */
export const REMINDER_TEMPLATE_VERSION = "1.0.0";