/**
 * Weekly Digest Email Template
 * 
 * Reference for the HTML template used in src/lib/email.ts.
 * The actual HTML is generated by the `weeklyDigestHtml()` function.
 */
export const DIGEST_TEMPLATE_VERSION = "1.0.0";