/**
 * Welcome Email Template
 * 
 * This is a reference for the HTML template used in src/lib/email.ts.
 * The actual HTML is generated by the `welcomeEmailHtml()` function.
 * 
 * Customization: Edit the `welcomeEmailHtml()` function in src/lib/email.ts
 * and rebuild the app.
 */
export const WELCOME_TEMPLATE_VERSION = "1.0.0";